server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: SCHOOL
  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate :
      ddl-auto: create
    database: postgresql
    database-platform : org.hibernate.dialect.PostgreSQLDialect


